### ISSUE TITLE
How to use the pretrained object pose estimation model for end to end eval.

### ISSUE THREAD

**Issue by yikakabu** [jimmyyhwu/pose-interpreter-networks#10]
Hi, Jimmy.
When I loaded the checkpoint of floating_kinect1_object in the end_to_end_eval.ipynb. There is a error 

> RuntimeError: Given groups=1, weight[64, 3, 7, 7], so expected input[1, 1, 240, 320] to have 3 channels, but got 1 channels instead

So I wander could the object chekpoint be used to end_to_end_eval/visualize.
Thanks you.

**Comment by dingshenglan** [comment]
I met this problem，just because the mask png has only one channel.

**Comment by jimmyyhwu** [comment]
No, the end-to-end expects a mask input, so you can't use floating_kinect1_object.

**Comment by yikakabu** [comment]
@jimmyyhwu 
I see. Thank you for your reply.
