### ISSUE TITLE
a question about making own datasets 

### ISSUE THREAD

**Issue by dingshenglan** [jimmyyhwu/pose-interpreter-networks#14]
Hello, I now mark each image in my dataset with ”labelme“ and convert the annotation.json format to coco format, but these files are one by one, how to properly merge a annotation file, just like the annotations file you provide in Oilchangedatasets?
![image](https://user-images.githubusercontent.com/34231078/56178671-a805db00-6035-11e9-95d3-7ed905db812d.png)

**Comment by jimmyyhwu** [comment]
You would write your own script to do that. See the COCO [API](https://github.com/cocodataset/cocoapi) and [data format](http://cocodataset.org/#format-data).

I would make sure the image ID and annotation ID are unique after merging, and that categories and category IDs are the same for all images.
