### ISSUE TITLE
Issue with Segmentation Eval 403 Forbidden

### ISSUE THREAD

**Issue by SpencerTrihus** [jimmyyhwu/pose-interpreter-networks#21]
Hi Jimmy,

I have downloaded the pretrained datasets, however when I attempt to run the segmentation eval Jupyter notebook. I receive an error in the third block. It seems that the code is downloading a checkpoint from a princeton website. Attempting to visit this site gives me a 403 Forbidden error. The address is: https://tigress-web.princeton.edu/~fy/drn/models/drn_d_22-4bd2f8ea.pth. 

Do users need special permission for this?

Thanks

**Comment by jimmyyhwu** [comment]
I just updated the URL, give it another try!

**Comment by SpencerTrihus** [comment]
I am still receiving the same error with the following line of code:
segm_model = segm_models.DRNSeg(segm_cfg.arch, segm_cfg.data.classes, None, pretrained=True)

More specifically, the above line eventually calls this line during class initiation:
model.load_state_dict(model_zoo.load_url(model_urls['drn-d-22']))

I still receive a 403 Forbidden error. I have also attempted to simply open the link I posted above to the same result.

Thanks

**Comment by jimmyyhwu** [comment]
Sorry for the confusion, you have to pull my new commit (51242d0) to update the URL.
