### ISSUE TITLE
No such file or directory: 'data/OilChangeDataset\\annotations\\val_20171103_OilChange.json'

### ISSUE THREAD

**Issue by capslocknanda** [jimmyyhwu/pose-interpreter-networks#24]
I can not unzip the oil change dataset. Its showing corrupted file. 
Kindly help, please !!!!

**Comment by jimmyyhwu** [comment]
The download [script](https://github.com/jimmyyhwu/pose-interpreter-networks/blob/master/download_data.sh) should automatically extract the files for you. I just checked and the script is still working.

You can run it using:

```bash
./download_data.sh
```

If the file is corrupted, you could try removing the downloaded files and running the script again.

**Comment by capslocknanda** [comment]
It worked. Thank you very much.

**Comment by arturohernandez10** [comment]
Hello,

I have downloaded the tar file several times. And I get the meshes and images folders. I've open files in both and they look good. But there are no annotations files. And I get the same error. Any suggestions?

**Comment by jimmyyhwu** [comment]
They should still be in the tar file, but here is a zip with just the annotations: [annotations.zip](https://github.com/jimmyyhwu/pose-interpreter-networks/files/7836179/annotations.zip)
