### ISSUE TITLE
Rendering folder calling issue

### ISSUE THREAD

**Issue by meghalD** [jimmyyhwu/pose-interpreter-networks#26]
the code for segmentation works fine but creates a problem for me in end_to_end_visualization.py and pose_estimation/demo.py in importing 
from dataset import oilchange_scene

I think when at folder pose_estimation it needs to access oilchange.py file which is in dataset folder, and from folder I cannot import this way. Hence, it shows and error. Please suggest a work around for this.

**Comment by jimmyyhwu** [comment]
I think [this line](https://github.com/jimmyyhwu/pose-interpreter-networks/blob/master/pose_estimation/render_pose.py#L6) is supposed to take care of the import problem. I did not have to add any workaround to run the notebooks. Maybe you could try opening `jupyter notebook` in the same directory that the notebook is in?
