### ISSUE TITLE
Why do we need blender for demo?

### ISSUE THREAD

**Issue by vikas-baghel** [jimmyyhwu/pose-interpreter-networks#30]
Hi, thanks for your great work. I wanted to see the results of your work, i.e. I will give a RGB image and expect 6dposes. I believe that blender was used to create the synthetic dataset for training Pose interpreter network. My question is why do we need blender for seeing the results.

My other question is if we require blender then how to use it on some online platform like google collab?

**Comment by jimmyyhwu** [comment]
Blender is used to render visualizations of the pose predictions. If you don't need to visualize the predicted poses, then you could skip Blender.

I believe Blender should work in Colab, but I have not tried it and am not able to provide support for that.

**Comment by vikas-baghel** [comment]
Thanks, I will try to find a way to use blender on colab.
